name: Publish Docker

on:
  push:
    branches: [ main ]
  release:
    types: [published, created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ghcr.io/energywebfoundation/siwe_oidc
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        tag_names: true
        tag_semver: true
        snapshot: true
        buildargs: PROJECT_ID=${{ secrets.PROJECT_ID }}
